namespace Grinspector.Generator;

internal static class Templates
{
    public const string Wrapper = @"// <auto-generated/>
#nullable enable

namespace {{NAMESPACE}}
{
    public class {{TYPE_NAME}}_Privates
    {
        private readonly {{FULL_TYPE_NAME}} _instance;

        public {{TYPE_NAME}}_Privates({{FULL_TYPE_NAME}} instance)
        {
            if (instance == null)
                throw new System.ArgumentNullException(nameof(instance));
            _instance = instance;
        }

{{MEMBERS}}
    }

    public static class {{TYPE_NAME}}_Privates_Static
    {
{{STATIC_MEMBERS}}
    }
}
";

    public const string Method = @"        public {{RETURN_TYPE}} {{METHOD_NAME}}({{PARAMETERS}})
        {
            var methodInfo = typeof({{TYPE_FULL_NAME}}).GetMethod(""{{METHOD_NAME}}"", 
                System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);

            if (methodInfo == null)
                throw new System.InvalidOperationException(""Method '{{METHOD_NAME}}' not found"");

            {{INVOKE}}
        }

";

    public const string StaticMethod = @"        public static {{RETURN_TYPE}} {{METHOD_NAME}}({{PARAMETERS}})
        {
            var methodInfo = typeof({{TYPE_FULL_NAME}}).GetMethod(""{{METHOD_NAME}}"", 
                {{BINDING_FLAGS}});

            if (methodInfo == null)
                throw new System.InvalidOperationException(""Method '{{METHOD_NAME}}' not found"");

            {{INVOKE}}
        }

";

    public const string Property = @"        public {{PROPERTY_TYPE}} {{PROPERTY_NAME}}
        {
{{GETTER}}{{SETTER}}        }

";

    public const string StaticProperty = @"        public static {{PROPERTY_TYPE}} {{PROPERTY_NAME}}
        {
{{GETTER}}{{SETTER}}        }

";

    public const string PropertyGetter = @"            get
            {
                var propertyInfo = typeof({{TYPE_FULL_NAME}}).GetProperty(""{{PROPERTY_NAME}}"", 
                    System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);

                if (propertyInfo == null)
                    throw new System.InvalidOperationException(""Property '{{PROPERTY_NAME}}' not found"");

                return ({{PROPERTY_TYPE}})propertyInfo.GetValue(_instance)!;
            }
";

    public const string StaticPropertyGetter = @"            get
            {
                var propertyInfo = typeof({{TYPE_FULL_NAME}}).GetProperty(""{{PROPERTY_NAME}}"", 
                    {{BINDING_FLAGS}});

                if (propertyInfo == null)
                    throw new System.InvalidOperationException(""Property '{{PROPERTY_NAME}}' not found"");

                return ({{PROPERTY_TYPE}})propertyInfo.GetValue(null)!;
            }
";

    public const string PropertySetter = @"            set
            {
                var propertyInfo = typeof({{TYPE_FULL_NAME}}).GetProperty(""{{PROPERTY_NAME}}"", 
                    System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);

                if (propertyInfo == null)
                    throw new System.InvalidOperationException(""Property '{{PROPERTY_NAME}}' not found"");

                propertyInfo.SetValue(_instance, value);
            }
";

    public const string StaticPropertySetter = @"            set
            {
                var propertyInfo = typeof({{TYPE_FULL_NAME}}).GetProperty(""{{PROPERTY_NAME}}"", 
                    {{BINDING_FLAGS}});

                if (propertyInfo == null)
                    throw new System.InvalidOperationException(""Property '{{PROPERTY_NAME}}' not found"");

                propertyInfo.SetValue(null, value);
            }
";

    public const string Field = @"        public {{FIELD_TYPE}} {{FIELD_NAME}}
        {
{{GETTER}}{{SETTER}}        }

";

    public const string StaticField = @"        public static {{FIELD_TYPE}} {{FIELD_NAME}}
        {
{{GETTER}}{{SETTER}}        }

";

    public const string FieldGetter = @"            get
            {
                var fieldInfo = typeof({{TYPE_FULL_NAME}}).GetField(""{{FIELD_NAME}}"", 
                    System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);

                if (fieldInfo == null)
                    throw new System.InvalidOperationException(""Field '{{FIELD_NAME}}' not found"");

                return ({{FIELD_TYPE}})fieldInfo.GetValue(_instance)!;
            }
";

    public const string StaticFieldGetter = @"            get
            {
                var fieldInfo = typeof({{TYPE_FULL_NAME}}).GetField(""{{FIELD_NAME}}"", 
                    {{BINDING_FLAGS}});

                if (fieldInfo == null)
                    throw new System.InvalidOperationException(""Field '{{FIELD_NAME}}' not found"");

                return ({{FIELD_TYPE}})fieldInfo.GetValue(null)!;
            }
";

    public const string FieldSetter = @"            set
            {
                var fieldInfo = typeof({{TYPE_FULL_NAME}}).GetField(""{{FIELD_NAME}}"", 
                    System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);

                if (fieldInfo == null)
                    throw new System.InvalidOperationException(""Field '{{FIELD_NAME}}' not found"");

                fieldInfo.SetValue(_instance, value);
            }
";

    public const string StaticFieldSetter = @"            set
            {
                var fieldInfo = typeof({{TYPE_FULL_NAME}}).GetField(""{{FIELD_NAME}}"", 
                    {{BINDING_FLAGS}});

                if (fieldInfo == null)
                    throw new System.InvalidOperationException(""Field '{{FIELD_NAME}}' not found"");

                fieldInfo.SetValue(null, value);
            }
";

    public const string Constructor = @"        public static {{TYPE_FULL_NAME}} CreateInstance({{PARAMETERS}})
        {
            var ctorInfo = typeof({{TYPE_FULL_NAME}}).GetConstructor(
                System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic,
                null,
                new System.Type[] { {{PARAM_TYPES}} },
                null);

            if (ctorInfo == null)
                throw new System.InvalidOperationException(""Constructor not found"");

            {{INVOKE}}
        }

";
}
