namespace Grinspector.Generator;

internal static class Templates
{
    public const string InternalsWrapper = @"// <auto-generated/>
#nullable enable

namespace {{NAMESPACE}}
{
    public class {{TYPE_NAME}}_Privates
    {
        private readonly {{FULL_TYPE_NAME}} _instance;

        public {{TYPE_NAME}}_Privates({{FULL_TYPE_NAME}} instance)
        {
            if (instance == null)
                throw new System.ArgumentNullException(nameof(instance));
            _instance = instance;
        }

{{MEMBERS}}
    }
}
";

    public const string MethodWrapper = @"        public {{RETURN_TYPE}} {{METHOD_NAME}}({{PARAMETERS}})
        {
            var methodInfo = typeof({{TYPE_FULL_NAME}}).GetMethod(""{{METHOD_NAME}}"", 
                System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);

            if (methodInfo == null)
                throw new System.InvalidOperationException(""Method '{{METHOD_NAME}}' not found"");

            {{INVOKE}}
        }

";

    public const string PropertyWrapper = @"        public {{PROPERTY_TYPE}} {{PROPERTY_NAME}}
        {
{{GETTER}}{{SETTER}}        }

";

    public const string PropertyGetter = @"            get
            {
                var propertyInfo = typeof({{TYPE_FULL_NAME}}).GetProperty(""{{PROPERTY_NAME}}"", 
                    System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);

                if (propertyInfo == null)
                    throw new System.InvalidOperationException(""Property '{{PROPERTY_NAME}}' not found"");

                return ({{PROPERTY_TYPE}})propertyInfo.GetValue(_instance)!;
            }
";

    public const string PropertySetter = @"            set
            {
                var propertyInfo = typeof({{TYPE_FULL_NAME}}).GetProperty(""{{PROPERTY_NAME}}"", 
                    System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);

                if (propertyInfo == null)
                    throw new System.InvalidOperationException(""Property '{{PROPERTY_NAME}}' not found"");

                propertyInfo.SetValue(_instance, value);
            }
";

    public const string FieldWrapper = @"        public {{FIELD_TYPE}} {{FIELD_NAME}}
        {
{{GETTER}}{{SETTER}}        }

";

    public const string FieldGetter = @"            get
            {
                var fieldInfo = typeof({{TYPE_FULL_NAME}}).GetField(""{{FIELD_NAME}}"", 
                    System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);

                if (fieldInfo == null)
                    throw new System.InvalidOperationException(""Field '{{FIELD_NAME}}' not found"");

                return ({{FIELD_TYPE}})fieldInfo.GetValue(_instance)!;
            }
";

    public const string FieldSetter = @"            set
            {
                var fieldInfo = typeof({{TYPE_FULL_NAME}}).GetField(""{{FIELD_NAME}}"", 
                    System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);

                if (fieldInfo == null)
                    throw new System.InvalidOperationException(""Field '{{FIELD_NAME}}' not found"");

                fieldInfo.SetValue(_instance, value);
            }
";
}
